from ...i18n import m_

LOCALES = {
    'de': 'de_DE',
    'en': 'en_US'
}


WEATHER_DESCRIPTON = {
    200: m_('thunderstorm with light rain'),
    201: m_('thunderstorm with rain'),
    202: m_('thunderstorm with heavy rain'),
    210: m_('light thunderstorm'),
    211: m_('thunderstorm'),
    212: m_('heavy thunderstorm'),
    221: m_('ragged thunderstorm'),
    230: m_('thunderstorm with light drizzle'),
    231: m_('thunderstorm with drizzle'),
    232: m_('thunderstorm with heavy drizzle'),
    300: m_('light intensity drizzle'),
    301: m_('drizzle'),
    302: m_('heavy intensity drizzle'),
    310: m_('light intensity drizzle rain'),
    311: m_('drizzle rain'),
    312: m_('heavy intensity drizzle rain'),
    313: m_('shower rain and drizzle'),
    314: m_('heavy shower rain and drizzle'),
    321: m_('shower drizzle'),
    500: m_('light rain'),
    501: m_('moderate rain'),
    502: m_('heavy intensity rain'),
    503: m_('very heavy rain'),
    504: m_('extreme rain'),
    511: m_('freezing rain'),
    520: m_('light intensity shower rain'),
    521: m_('shower rain'),
    522: m_('heavy intensity shower rain'),
    531: m_('ragged shower rain'),
    600: m_('light snow'),
    601: m_('snow'),
    602: m_('heavy snow'),
    611: m_('sleet'),
    612: m_('shower sleet'),
    615: m_('light rain and snow'),
    616: m_('rain and snow'),
    620: m_('light shower snow'),
    621: m_('shower snow'),
    622: m_('heavy shower snow'),
    701: m_('mist'),
    711: m_('smoke'),
    721: m_('haze'),
    731: m_('sand, dust whirls'),
    741: m_('fog'),
    751: m_('sand'),
    761: m_('dust'),
    762: m_('volcanic ash'),
    771: m_('squalls'),
    781: m_('tornado'),
    800: m_('clear sky'),
    801: m_('few clouds'),
    802: m_('scattered clouds'),
    803: m_('broken clouds'),
    804: m_('overcast clouds'),
    900: m_('tornado'),
    901: m_('tropical storm'),
    902: m_('hurricane'),
    903: m_('cold'),
    904: m_('hot'),
    905: m_('windy'),
    906: m_('hail'),
    951: m_('calm'),
    952: m_('light breeze'),
    953: m_('gentle breeze'),
    954: m_('moderate breeze'),
    955: m_('fresh breeze'),
    956: m_('strong breeze'),
    957: m_('high wind, near gale'),
    958: m_('gale'),
    959: m_('severe gale'),
    960: m_('storm'),
    961: m_('violent storm'),
    962: m_('hurricane'),
}
